name = "KamiMod"
license = "MIT"
licenselink = "https://github.com/8hobbies/KamiMod/blob/master/LICENSE"
description = "A fast, clean, responsive Hugo theme"
homepage = "https://github.com/8hobbies/KamiMod"
demosite = "https://kamimod.8hob.io"
tags = [
  "responsive",
  "simple",
  "clean",
  "light",
  "dark",
  "blog",
  "minimalist",
  "highlight.js",
  "search"
]
features = [
  "responsive",
  "single-column",
  "blog",
  "cover-image",
  "table-of-contents",
  "opengraph",
  "highlight.js",
  "favicon",
  "archive",
  "share-icons",
  "cover",
  "multilingual",
  "social-icons",
  "minified-assets",
  "theme-toggle",
  "menu-location-indicator",
  "scroll-to-top",
  "search"
]
<<<<<<< HEAD
min_version = "0.126.0"
=======
min_version = "0.146.0"
>>>>>>> upstream/master

[author]
  name = "8 Hobbies JavaScript Blog"
  homepage = "https://8hob.io"

[original]
  author = "Aditya Telange"
  name = "PaperMod"
  homepage = "https://adityatelange.github.io/hugo-PaperMod/"
  repo = "https://github.com/adityatelange/hugo-PaperMod/"
