blank_issues_enabled: false
contact_links:
  - name: KamiMod Discussions
    url: https://github.com/8hobbies/KamiMod/discussions
    about: Please ask and answer questions/doubts here, DO NOT open an issue for questions.
